export enum PurpleColors {
  Lavender = '#e6e6fa',
  Thistle = '#d8bfd8',
  Plum = '#dda0dd',
  Mauve = '#e0b0ff',
  Wisteria = '#c9a0dc',
  Orchid = '#da70d6',
  MediumOrchid = '#ba55d3',
  MediumPurple = '#9370db',
  Amethyst = '#9966cc',
  BlueViolet = '#8a2be2',
  Purple = '#800080',
  Violet = '#8f00ff',
  Magenta = '#ff00ff',
  Grape = '#6f2da8',
  Indigo = '#4b0082',
  Eggplant = '#301934',
}

export const PURPLE_COLORS = [
  {
    name: 'Lavender',
    nameZh: '薰衣草',
    hex: PurpleColors.Lavender,
    desc: '淡紫偏粉',
  },
  {
    name: 'Thistle',
    nameZh: '蓟紫色',
    hex: PurpleColors.Thistle,
    desc: '带灰调',
  },
  {
    name: 'Plum',
    nameZh: '李子紫',
    hex: PurpleColors.Plum,
    desc: '柔和温暖',
  },
  {
    name: 'Mauve',
    nameZh: '淡紫色',
    hex: PurpleColors.Mauve,
    desc: '烟粉色调',
  },
  {
    name: 'Wisteria',
    nameZh: '紫藤色',
    hex: PurpleColors.Wisteria,
    desc: '温柔浅紫',
  },
  {
    name: 'Orchid',
    nameZh: '兰花紫',
    hex: PurpleColors.Orchid,
    desc: '偏红亮紫',
  },
  {
    name: 'Medium Orchid',
    nameZh: '中兰花紫',
    hex: PurpleColors.MediumOrchid,
    desc: '稍深更艳',
  },
  {
    name: 'Medium Purple',
    nameZh: '中紫色',
    hex: PurpleColors.MediumPurple,
    desc: '柔和略蓝',
  },
  {
    name: 'Amethyst',
    nameZh: '紫水晶色',
    hex: PurpleColors.Amethyst,
    desc: '经典冷紫',
  },
  {
    name: 'Blue Violet',
    nameZh: '蓝紫色',
    hex: PurpleColors.BlueViolet,
    desc: '较冷',
  },
  {
    name: 'Purple',
    nameZh: '标准紫色',
    hex: PurpleColors.Purple,
    desc: '饱和且暗',
  },
  {
    name: 'Violet',
    nameZh: '紫罗兰',
    hex: PurpleColors.Violet,
    desc: '更偏蓝光谱',
  },
  {
    name: 'Magenta',
    nameZh: '洋红色',
    hex: PurpleColors.Magenta,
    desc: '红紫交界',
  },
  {
    name: 'Grape',
    nameZh: '葡萄紫',
    hex: PurpleColors.Grape,
    desc: '饱和深紫',
  },
  {
    name: 'Indigo',
    nameZh: '靛青色',
    hex: PurpleColors.Indigo,
    desc: '蓝紫之间',
  },
  {
    name: 'Eggplant',
    nameZh: '茄子紫',
    hex: PurpleColors.Eggplant,
    desc: '极深紫红',
  },
]
